# web port
server:
  port: 8081
# log config
logging:
  config: classpath:logback.xml

# xxl-job
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### executor address
    executor:
      appname: elastic-task-executor
      ip:
      port: 9999
      ### log path
      logpath: /Users/wangzhiyong/tmp/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### access token
    accessToken: